#!/usr/bin/env bash
# Configure HAProxy to balance load between
# two web servers with custom headers

install_and_configure_haproxy() {
	apt-get -y update
	apt-get -y upgrade

	apt-get -y install software-properties-common
    add-apt-repository -y ppa:vbernat/haproxy-2.5
    apt-get -y update

	apt-get -y install haproxy

	cp /etc/haproxy/haproxy.cfg{,.orig}

	cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 373485-web-01 3.85.168.142:80 check
    server 373485-web-02 54.236.231.114:80 check
EOL

	service haproxy restart

}

install_and_configure_haproxy
